name: List current files
on:
  workflow_dispatch:
jobs:
  list_files:
    name: List the files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application project repository
        uses: actions/checkout@v3
      - name: Execute LS 
        run: ls -la