name: Deploy Platformatic DB application to the cloud
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application project repository
        uses: actions/checkout@v3
      - name: npm install --omit=dev
        run: npm install --omit=dev
      - name: Deploy project
        uses: platformatic/onestep@8db3ae99b676de64db5ff2a3ea2aa4d65c025687
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_API_KEY }}
          platformatic_config_path: ./platformatic.db.json
          platformatic_workspace_id: 4068aa66-ec15-4d4b-b990-05d8b30e4e63




